### ISSUE TITLE
RFC: Tag open/close

### ISSUE THREAD

**Issue by shabbyrobe** [shabbyrobe/tempe#2]
The `{{` and `}}` tag open/close tokens used by Tempe v1 are very familiar to users of Twig, Jinja, Mustache, etc. These are mostly used for web templating, but I've used Tempe's guts to write quick templating DSLs for a few applications now and they fall down pretty badly in certain contexts, particularly when attempting code generation for a curly brace heavy language.

It gets quite unreadable when you see a few tags run together, particularly with unnamed block closes:

```
from bad:
    {{ get foo }}{{ get bar }}{{ get baz }}
to worse:
    {{#get _first_|show}}Yep!{{/}}{{#get _first_|not|show}}Nup!{{/}}
```

`{{/}}{{#`? OUCH my eyes.

It's pretty much a lock that `{{` and `}}` have to go, but what to replace them with?

The key criteria are:
- Readability, particularly when block closes are run together
- Ergonomics - if it's hard to type, who would use it?
- Aesthetics - There are some UGLY template languages out there.
- Uniqueness - Must not clash with existing domains, whether they be mark up, mark down or code.

The best idea I have so far is to replace `{{` with `<[` and `}}` with `]>`.

Readability is OK:

```
<[#get _first_|show]>Yep!<[/]><[#get _first_|not|show]>Nup!<[/]>
```

Ergonomics are worse than `{{`. Muscle memory may improve this, but I've noticed I have a tendency to type `<{` by accident as I lag releasing the shift key.

Aesthetics aren't great. There's sort of a half-cocked XML thing going on.

Uniqueness seems good so far - I have not found a single programming language, template language, mark up language or mark down language that they clash with.

Here's a comparison of the current syntax for block iteration and the proposed syntax:
![screenshot - 080515 - 10 11 29](https://cloud.githubusercontent.com/assets/288426/7528410/aa1165ac-f56a-11e4-828f-a71e13e5efa4.png)

I actually think I quite dislike `<[` and `]>`, but at least it's a start.

**Comment by shabbyrobe** [comment]
Paging @monofonik

**Comment by shabbyrobe** [comment]
What about something similar to Jinja/twig? No need to have `%}` for closing: `}` will do. The drawback is it needs three escapers, but you're less likely to need them: `{%;` `{#;` and `{/;`.

![screenshot - 090515 - 14 36 09](https://cloud.githubusercontent.com/assets/288426/7548696/12a2016e-f659-11e4-925d-23d3423f242b.png)

**Comment by monofonik** [comment]
Ergonomics is more important than readability. Yes, readability is crucial for the comprehension of a language, but if it's too much of a pain in the ass to write the thing, no one will ever get to read it! 

`{{yep}}{{nup}}` doesn't read particularly well, but `<[yep]><[nup]>` has twice the number of special characters. 

I think you're onto something with the Jinja variant... less characters, readable, it's ticking the boxes. Extra escapers doesn't really register as a negative for me, it's so rare that they're even used.

**Comment by shabbyrobe** [comment]
We can get away from the Jinja clash by trotting out our old friend `=`, too, i.e. `{%` becomes `{=`.

**Comment by shabbyrobe** [comment]
This has been merged into master. Even if we don't stick with it or tweak it, it's a step in the right direction. I'll leave the issue open until I evaluate whether there are any clashes with any of the targets.

I have a lingering concern: I'm a little bit worried the single closing curly could be confusing if a tempe tag is to be followed with a curly brace:
```
var obj = {{#each foo }
    "{= get _key_ }": "{= get _value_ }",
{/}};
```
Code generation in curly heavy languages is exactly why I wanted to get rid of curlies in the first place.
